"""pcp architecture-justification — auto-generated rollup of every module's
logic_tier/build_vs_buy decisions (see CLAUDE.md's Logic-Tier Selection
philosophy). Same posture as provenance.md: pure aggregation over what's
already on disk (spec.yaml + acceptance.yaml), no LLM call, never
hand-edited -- the rationale lives once, in the structured field; this is a
view over it, not a second place to author rationale."""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, get_modules_dir, NoPCPDir

console = Console()

TIER_LABELS = {
    1: "Deterministic", 2: "Solver", 3: "ML/statistical",
    4: "RAG", 5: "Cached reuse", 6: "Deep-think LLM",
}


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def build_architecture_justification(pcp_dir: Path) -> dict:
    """Pure aggregation, no LLM. Returns per-module spec-level build_vs_buy
    plus per-criterion logic_tier/build_vs_buy, and a coercion-flag count so
    a placeholder decision (never actually deliberated) is visible, not
    indistinguishable from a real one."""
    modules_dir = get_modules_dir(pcp_dir)
    modules = []
    flagged_count = 0
    tier_counts = {t: 0 for t in TIER_LABELS}

    if modules_dir.exists():
        for mod_path in sorted(p for p in modules_dir.iterdir() if p.is_dir()):
            spec = _load_yaml(mod_path / "spec.yaml")
            acceptance = _load_yaml(mod_path / "acceptance.yaml")
            if not spec and not acceptance:
                continue

            module_bvb = spec.get("build_vs_buy")
            if module_bvb and "not specified by generator" in module_bvb.get("rationale", "").lower():
                flagged_count += 1

            criteria = []
            for c in acceptance.get("criteria", []):
                tier = c.get("logic_tier")
                if tier in tier_counts:
                    tier_counts[tier] += 1
                bvb = c.get("build_vs_buy") or {}
                flagged = "not specified by generator" in bvb.get("rationale", "").lower()
                if flagged:
                    flagged_count += 1
                criteria.append({
                    "id": c.get("id"),
                    "description": c.get("description"),
                    "logic_tier": tier,
                    "build_vs_buy": bvb,
                    "flagged": flagged,
                })

            modules.append({
                "module": mod_path.name,
                "module_build_vs_buy": module_bvb,
                "criteria": criteria,
            })

    return {
        "modules": modules,
        "tier_counts": tier_counts,
        "flagged_count": flagged_count,
    }


def _render_markdown(data: dict, timestamp: str) -> str:
    lines = [
        "# Architecture Justification",
        "",
        f"_Auto-generated by `pcp architecture-justification` at {timestamp}. "
        "Never hand-edit — the rationale lives in each module's spec.yaml/acceptance.yaml; "
        "this is a rollup view, not a second place to author it._",
        "",
        "## Logic-Tier Distribution",
        "",
        "| Tier | Label | Criteria |",
        "|---|---|---|",
    ]
    for tier, label in TIER_LABELS.items():
        lines.append(f"| {tier} | {label} | {data['tier_counts'].get(tier, 0)} |")
    lines.append("")

    if data["flagged_count"]:
        lines.append(
            f"**{data['flagged_count']} decision(s) are coerced placeholders** "
            "(missing/malformed at generation time, not a real deliberation) — flagged below, review before trusting."
        )
        lines.append("")

    if not data["modules"]:
        lines.append("_No modules found — nothing to report yet._")
        return "\n".join(lines)

    for m in data["modules"]:
        lines.append(f"## Module: `{m['module']}`")
        lines.append("")
        mbvb = m.get("module_build_vs_buy")
        if mbvb:
            lines.append(f"**Module-level build-vs-buy:** `{mbvb.get('decision')}` — {mbvb.get('rationale', '')}")
            candidates = mbvb.get("candidates_considered") or []
            if candidates:
                lines.append(f"Candidates considered: {', '.join(candidates)}")
            lines.append("")

        if m["criteria"]:
            lines.append("| Criterion | Tier | Build-vs-buy | Rationale |")
            lines.append("|---|---|---|---|")
            for c in m["criteria"]:
                tier_label = TIER_LABELS.get(c["logic_tier"], "?")
                bvb = c["build_vs_buy"] or {}
                flag = " ⚠" if c["flagged"] else ""
                lines.append(
                    f"| {c['id']}: {c['description']} | {c['logic_tier']} ({tier_label}){flag} "
                    f"| {bvb.get('decision', '?')} | {bvb.get('rationale', '')} |"
                )
            lines.append("")

    return "\n".join(lines)


def write_architecture_justification(pcp_dir: Path) -> Path:
    data = build_architecture_justification(pcp_dir)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    md = _render_markdown(data, timestamp)
    out = pcp_dir / "architecture_justification.md"
    out.write_text(md)
    return out


@click.command(name="architecture-justification")
@click.option("--path", "project_path", type=click.Path(), default=None)
@click.option("--json", "output_json", is_flag=True, help="Print raw JSON instead of writing architecture_justification.md.")
def architecture_justification(project_path: str | None, output_json: bool):
    """Roll up every module's logic_tier/build_vs_buy decisions into architecture_justification.md."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if output_json:
        click.echo(json.dumps(build_architecture_justification(pcp_dir), indent=2, default=str))
        return

    out_path = write_architecture_justification(pcp_dir)
    console.print(f"[green]Architecture justification written[/green] -> {out_path.relative_to(pcp_dir.parent)}")
