"""pcp design-audit — PCP Design lifecycle, stage 5 (Audit/rollup).

Feature Exposure Ladder: for every UI-facing acceptance criterion in a
project, classifies how discoverable it actually is to an end user, based
on the design_justification stage 2 (Decide) already recorded (or not) on
that criterion. Pure aggregation over what's already on disk -- no LLM,
never hand-edited, same posture as architecture_justification.py, but a
different audience: this is for product/PM ("can a user find and use this"),
architecture_justification.md is for engineering ("was this the right
technical call").

Maps directly onto Google's HEART framework's Adoption pillar, computed
statically from declared intent rather than live usage telemetry (Happiness/
Engagement/Retention need real instrumentation -- a separate, deferred
build-vs-buy decision, not something inferable from a build-time audit).
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, get_modules_dir, NoPCPDir
from pcp.commands.build import _is_ui_facing_criterion

console = Console()

RUNG_LABEL = {
    1: "Built, Hidden",
    2: "Exposed, Undiscoverable",
    3: "Exposed, Discoverable",
    4: "Exposed, Enriched",
}

# Crude, deterministic JTBD-shape check: a real "when X, do Y" conditional
# framing vs. a bare feature-name restatement. Good enough as a rung-3→4
# gate; false negatives just mean a genuinely good framing sits one rung
# lower than it deserves, which is a safe direction to err in.
_JTBD_MARKERS = ("when ", "if ", "whenever ")


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def _classify_rung(criterion: dict) -> int:
    dj = criterion.get("design_justification")
    if dj is None:
        return 1
    checklist = dj.get("checklist_passed") or []
    jtbd = (dj.get("jtbd_framing") or "").strip()
    if not checklist and not jtbd:
        return 2
    if jtbd and any(m in jtbd.lower() for m in _JTBD_MARKERS) and checklist:
        return 4
    return 3


def build_design_audit(pcp_dir: Path) -> dict:
    """Pure aggregation, no LLM -- safe to call at any point."""
    modules_dir = get_modules_dir(pcp_dir)
    modules = []
    rung_counts = {r: 0 for r in RUNG_LABEL}
    total_ui_criteria = 0

    if modules_dir.exists():
        for mod_path in sorted(p for p in modules_dir.iterdir() if p.is_dir()):
            acceptance = _load_yaml(mod_path / "acceptance.yaml")
            ui_criteria = []
            for c in acceptance.get("criteria", []):
                if not _is_ui_facing_criterion(c):
                    continue
                rung = _classify_rung(c)
                rung_counts[rung] += 1
                total_ui_criteria += 1
                dj = c.get("design_justification") or {}
                ui_criteria.append({
                    "id": c.get("id"),
                    "description": c.get("description"),
                    "rung": rung,
                    "jtbd_framing": dj.get("jtbd_framing", ""),
                    "deviations_from_system": dj.get("deviations_from_system", ""),
                })
            if ui_criteria:
                modules.append({"module": mod_path.name, "criteria": ui_criteria})

    return {
        "modules": modules,
        "rung_counts": rung_counts,
        "total_ui_criteria": total_ui_criteria,
    }


def _render_markdown(data: dict, timestamp: str) -> str:
    lines = [
        "# Design Audit — Feature Exposure Ladder",
        "",
        f"_Auto-generated by `pcp design-audit` at {timestamp}. Never hand-edit — "
        "the rationale lives in each criterion's design_justification; this is a "
        "rollup view, not a second place to author it._",
        "",
        "PCP Design lifecycle, stage 5 (Audit/rollup). Maps to Google HEART's Adoption "
        "pillar, computed statically from declared intent, not live usage telemetry.",
        "",
        "## Rung Distribution",
        "",
        "| Rung | Label | Criteria |",
        "|---|---|---|",
    ]
    for rung, label in RUNG_LABEL.items():
        lines.append(f"| {rung} | {label} | {data['rung_counts'].get(rung, 0)} |")
    lines.append("")

    if not data["modules"]:
        lines.append("_No UI-facing criteria found yet._")
        return "\n".join(lines)

    for m in data["modules"]:
        lines.append(f"## Module: `{m['module']}`")
        lines.append("")
        lines.append("| Criterion | Rung | JTBD Framing |")
        lines.append("|---|---|---|")
        for c in m["criteria"]:
            flag = " ⚠" if c["rung"] == 1 else ""
            lines.append(f"| {c['id']}: {c['description']}{flag} | {c['rung']} ({RUNG_LABEL[c['rung']]}) | {c['jtbd_framing'] or '—'} |")
        lines.append("")

    return "\n".join(lines)


def write_design_audit(pcp_dir: Path) -> Path:
    data = build_design_audit(pcp_dir)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    md = _render_markdown(data, timestamp)
    out = pcp_dir / "design_audit.md"
    out.write_text(md)
    return out


@click.command(name="design-audit")
@click.option("--path", "project_path", type=click.Path(), default=None)
@click.option("--json", "output_json", is_flag=True, help="Print raw JSON instead of writing design_audit.md.")
def design_audit(project_path: str | None, output_json: bool):
    """Feature Exposure Ladder — roll up how discoverable UI-facing criteria actually are."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if output_json:
        click.echo(json.dumps(build_design_audit(pcp_dir), indent=2, default=str))
        return

    out_path = write_design_audit(pcp_dir)
    console.print(f"[green]Design audit written[/green] -> {out_path.relative_to(pcp_dir.parent)}")
