"""pcp gate — Layer 2 PR advisory gate (LLM alignment scoring)."""

import json
import subprocess
import sys
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, NoPCPDir
from pcp.schema.validator import load_yaml
from pcp.llm import client as llm

console = Console()

SYSTEM_PROMPT = """\
You are a program-context auditor reviewing a git diff for a pull request.
Score how well this PR moves the codebase toward the program objective and target state.

Output ONLY valid JSON — no prose, no markdown, no code fences.

Output schema:
{
  "alignment_score": 0.0,
  "summary": "one sentence",
  "advances": ["what this PR does well vs objective"],
  "regressions": ["what this PR moves away from objective or target_state"],
  "llm_rule_violations": ["ci_rules.yaml llm_semantic rule violations"],
  "recommendation": "merge | review | block"
}

alignment_score: 0.0 (moves away from objective) to 1.0 (perfectly aligned).
recommendation: 'merge' (score >= 0.7, no regressions), 'review' (score 0.4-0.7 or regressions),
  'block' (score < 0.4 or contradicts objective). Advisory only — never actually blocks merge.
"""


def _get_diff(base: str) -> str:
    result = subprocess.run(
        ["git", "diff", f"{base}...HEAD"],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git diff failed: {result.stderr.strip()}")
    return result.stdout[:12000]  # cap at 12k chars for LLM context


def _load_llm_rules(pcp_dir: Path) -> list[dict]:
    ci_rules_path = pcp_dir / "ci_rules.yaml"
    if not ci_rules_path.exists():
        return []
    data = load_yaml(ci_rules_path)
    return [r for r in data.get("rules", []) if r.get("check") == "llm_semantic"]


def _build_prompt(
    objective: str,
    target_state: str,
    current_state: str,
    diff: str,
    llm_rules: list[dict],
) -> str:
    parts = [f"## Program Objective\n\n{objective}\n"]

    if target_state:
        parts.append(f"## Target State\n\n{target_state}\n")

    if current_state:
        parts.append(f"## Current State (before this PR)\n\n{current_state}\n")

    if llm_rules:
        parts.append("## Advisory Rules (llm_semantic from ci_rules.yaml)\n")
        for r in llm_rules:
            parts.append(f"- [{r['id']}] {r['name']}: {r.get('description', '')}")
        parts.append("")

    parts.append(f"## PR Diff\n\n```diff\n{diff}\n```\n")
    parts.append("Score this PR's alignment with the objective and target state.")
    return "\n".join(parts)


def _render_markdown_comment(result: dict, base: str) -> str:
    score = result.get("alignment_score", 0.0)
    rec = result.get("recommendation", "review")
    emoji = {"merge": "✅", "review": "⚠️", "block": "🚫"}.get(rec, "⚠️")

    lines = [
        "## PCP Gate Report",
        "",
        f"**Alignment score:** {score:.0%}  {emoji} `{rec.upper()}`",
        f"**Base:** `{base}`",
        "",
        f"_{result.get('summary', '')}_",
        "",
    ]

    if result.get("advances"):
        lines += ["**What this PR advances:**", ""]
        for a in result["advances"]:
            lines.append(f"- ✓ {a}")
        lines.append("")

    if result.get("regressions"):
        lines += ["**Regressions / concerns:**", ""]
        for r in result["regressions"]:
            lines.append(f"- ⚠ {r}")
        lines.append("")

    if result.get("llm_rule_violations"):
        lines += ["**Advisory rule violations:**", ""]
        for v in result["llm_rule_violations"]:
            lines.append(f"- {v}")
        lines.append("")

    lines += [
        "---",
        "_This is advisory only — it does not block merge. "
        "Generated by [PCP](https://pcp-protocol.com) `pcp gate`._",
    ]
    return "\n".join(lines)


@click.command()
@click.option("--base", default="main", show_default=True,
              help="Base branch to diff against.")
@click.option("--json", "output_json", is_flag=True,
              help="Output raw JSON (for GitHub Action consumption).")
@click.option("--markdown", "output_markdown", is_flag=True,
              help="Output GitHub-flavored markdown PR comment.")
@click.option("--path", "project_path", type=click.Path(), default=None)
def gate(base: str, output_json: bool, output_markdown: bool, project_path: str | None):
    """Layer 2 PR gate — LLM alignment score (advisory). Never hard-blocks."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    try:
        diff = _get_diff(base)
    except RuntimeError as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if not diff.strip():
        console.print("[dim]No diff vs base branch — nothing to gate.[/dim]")
        sys.exit(0)

    objective = (pcp_dir / "objective.md").read_text() if (pcp_dir / "objective.md").exists() else ""
    target_state = (pcp_dir / "target_state.md").read_text() if (pcp_dir / "target_state.md").exists() else ""
    current_state = (pcp_dir / "current_state.md").read_text() if (pcp_dir / "current_state.md").exists() else ""
    llm_rules = _load_llm_rules(pcp_dir)

    if not output_json and not output_markdown:
        console.print(f"[dim]Scoring PR alignment vs {base}...[/dim]")

    try:
        result = llm.call_json(
            SYSTEM_PROMPT,
            _build_prompt(objective, target_state, current_state, diff, llm_rules),
            model=llm.JUDGE_MODEL, pcp_dir=pcp_dir, command="gate",
        )
    except RuntimeError as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)
    except ValueError as e:
        console.print(f"[red]LLM returned invalid JSON:[/red] {e}")
        sys.exit(2)

    from pcp import telemetry
    changed_files_result = subprocess.run(
        ["git", "diff", "--name-only", f"{base}...HEAD"], capture_output=True, text=True,
    )
    changed_files = [f.strip() for f in changed_files_result.stdout.splitlines() if f.strip()]
    telemetry.record(
        pcp_dir, cycle="qa", cycle_number=None, check="gate", control_id="CTRL-006",
        module=None, submodule=None, criterion_id=None, files=changed_files,
        result="block" if result.get("recommendation") == "block" else "pass",
        errors=result.get("regressions", []) + result.get("llm_rule_violations", []),
        error_count=len(result.get("regressions", [])) + len(result.get("llm_rule_violations", [])),
    )

    if output_json:
        click.echo(json.dumps(result, indent=2))
        sys.exit(0)

    if output_markdown:
        click.echo(_render_markdown_comment(result, base))
        sys.exit(0)

    # Rich terminal output
    score = result.get("alignment_score", 0.0)
    rec = result.get("recommendation", "review")
    color = {"merge": "green", "review": "yellow", "block": "red"}.get(rec, "yellow")

    console.print(f"\n[bold]Alignment:[/bold] [{color}]{score:.0%}[/{color}]  [{color}]{rec.upper()}[/{color}]")
    console.print(f"[dim]{result.get('summary', '')}[/dim]\n")

    for a in result.get("advances", []):
        console.print(f"  [green]✓[/green]  {a}")
    for r in result.get("regressions", []):
        console.print(f"  [yellow]⚠[/yellow]  {r}")
    for v in result.get("llm_rule_violations", []):
        console.print(f"  [yellow]⚠[/yellow]  {v}")

    console.print("\n[dim]Advisory only — does not block merge.[/dim]")
    sys.exit(0)
