"""pcp init — scaffold .pcp/ directory in a project."""

import re
import sys
from pathlib import Path

import click
from rich.console import Console

console = Console()


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[_-]", name) if part)

OBJECTIVE_TEMPLATE = """\
# Program Objective

## Why This Exists

[Describe the problem this program solves.]

## What Success Looks Like

1. [Measurable outcome 1]
2. [Measurable outcome 2]

## Out of Scope

- [What this program does NOT do]
"""

TARGET_STATE_TEMPLATE = """\
# Target State

[Describe what "done" looks like from a user/business perspective.
This is the ideal end state of the entire program.]
"""

ARCHITECTURE_TEMPLATE = """\
# Architecture

## Tech Stack

| Layer | Choice | Why |
|---|---|---|
| | | |

## Key Constraints

- [Constraint 1]

## Design Decisions

- [Decision and rationale]
"""

CI_RULES_TEMPLATE = """\
version: "1.0"
rules:
  # ── Modularity rules (generated by pcp init — do not remove) ──────────────
  # Philosophy: every module is a guest. It can leave without drama.
  # It can arrive without surgery. Nothing else should know about it
  # except the application registry.

  - id: MOD_001
    name: "No direct cross-module implementation imports"
    check: ast_pattern
    # matches: ../../other-module/src/  or  ../other-module/src/
    pattern: "from \\\\.\\\\./(\\\\.\\\\./)?[^/]+/src/"
    severity: hard_block
    message: "Modules must communicate through interfaces/, not by importing each other's src/. Move shared types to interfaces/."
    scope: ["*.py", "*.js", "*.jsx", "*.ts", "*.tsx", "*.go", "*.rb", "*.java", "*.php", "*.cs", "*.rs"]

  - id: MOD_002
    name: "No hardcoded module names as string literals in orchestrator"
    check: ast_pattern
    # catches brittle module-name strings that create implicit coupling
    pattern: "require\\\\(['\\\"]\\\\.\\\\./"
    severity: hard_block
    message: "Use the module registry pattern — app.register(Module) not require('../module')."
    scope: ["*.js", "*.jsx", "*.ts", "*.tsx"]

  - id: MOD_003
    name: "Every module must have a public interface file"
    check: file_exists
    target: "src/interfaces/I{module}.ts"
    severity: hard_block
    message: "Create src/interfaces/I{module}.ts defining what this module exposes. Other modules import only from here."

  - id: MOD_004
    name: "No shared global mutable state between modules"
    check: ast_pattern
    pattern: "global\\\\s+[A-Za-z_]\\\\w*\\\\s*="
    severity: hard_block
    message: "Global mutable state creates invisible coupling. Pass state through the registry or event bus."

  - id: MOD_005
    name: "Every module must have a feature flag"
    check: file_exists
    target: "src/modules/{module}/feature_flag.env"
    severity: hard_block
    message: "Create feature_flag.env with FEATURE_{MODULE}_ENABLED=false. All modules ship dark by default."

  # ── Security rules (generated by pcp init — do not remove) ────────────────
  - id: SEC_001
    name: "No hardcoded secrets, API keys, or tokens"
    check: ast_pattern
    pattern: "(password|secret|api[_-]?key|access[_-]?key|token)\\\\s*[:=]\\\\s*['\\\"][^'\\\"]{8,}['\\\"]"
    severity: hard_block
    message: "Load secrets from environment variables or a secrets manager, never hardcode them."
    scope: ["*.py", "*.js", "*.jsx", "*.ts", "*.tsx", "*.go", "*.rb", "*.java", "*.php", "*.cs", "*.rs"]

  - id: SEC_002
    name: "No dynamic code evaluation on untrusted input"
    check: ast_pattern
    pattern: "\\\\b(eval|exec)\\\\s*\\\\("
    severity: hard_block
    message: "Dynamic code evaluation on untrusted input is a code-injection vector. Use a safe parser or explicit dispatch instead."
    scope: ["*.py", "*.js", "*.jsx", "*.ts", "*.tsx", "*.go", "*.rb", "*.java", "*.php", "*.cs", "*.rs"]

  - id: SEC_003
    name: "No disabled TLS/certificate verification"
    check: ast_pattern
    pattern: "(verify\\\\s*=\\\\s*False|rejectUnauthorized\\\\s*:\\\\s*false|NODE_TLS_REJECT_UNAUTHORIZED\\\\s*=\\\\s*['\\\"]?0|ssl_verify\\\\s*=\\\\s*False|check_hostname\\\\s*=\\\\s*False)"
    severity: hard_block
    message: "Disabling certificate verification allows MITM attacks. Fix the underlying cert/trust-store issue instead."
    scope: ["*.py", "*.js", "*.jsx", "*.ts", "*.tsx", "*.go", "*.rb", "*.java", "*.php", "*.cs", "*.rs"]

  - id: SEC_004
    name: "No string-built SQL passed to execute()/query()"
    check: ast_pattern
    pattern: "\\\\.(execute|query)\\\\(\\\\s*(f['\\\"]|['\\\"][^'\\\"]*['\\\"]\\\\s*\\\\+)"
    severity: hard_block
    message: "Use parameterized queries (placeholders + a params argument), not f-strings or string concatenation."
    scope: ["*.py", "*.js", "*.jsx", "*.ts", "*.tsx", "*.go", "*.rb", "*.java", "*.php", "*.cs", "*.rs"]

  # ── Project rules (add yours below) ──────────────────────────────────────
"""

CONTROLS_TEMPLATE = """\
version: "1.0"
# Canonical catalog of gates PCP enforces on this project. This is the control
# catalog a future audit-evidence document (`pcp provenance`) reads to build a
# per-file/per-criterion compliance card. control ids here are written verbatim
# into .pcp/telemetry.jsonl's `control_id` field by every gate call site — do
# not rename an id without updating the code that emits it.
#
# ssdf_practice references NIST SP 800-218 (Secure Software Development
# Framework) practice ids. This is an informed mapping to give the catalog a
# recognizable compliance vocabulary — it is NOT a certified SSDF/CMMC
# assessment. Treat it as a jumpstart, not a certificate.
controls:
  - id: CTRL-001
    name: "Test suite must pass"
    layer: build-loop
    mechanism: "qa.run_test_suite"
    tool: "pytest | npm test | go test (auto-detected)"
    enforcement: hard_block
    description: "Full regression suite runs after every criterion's agent attempt and again at each wave-merge boundary. Blocks on failure. Skips (never blocks) if no test runner is detected — that skip is recorded, not silently treated as a pass."
    ssdf_practice: ["PW.7.2"]

  - id: CTRL-002
    name: "Lint clean on changed files"
    layer: build-loop
    mechanism: "qa.run_lint"
    tool: "ruff | eslint (auto-detected)"
    enforcement: hard_block
    description: "Lint scoped to the files changed by this criterion's attempt."
    ssdf_practice: ["PW.7.2"]

  - id: CTRL-003
    name: "SAST + secret scan clean"
    layer: build-loop
    mechanism: "qa.run_sast"
    tool: "semgrep"
    enforcement: hard_block
    description: "Static analysis + secret scan scoped to changed files. Skips (never blocks) if semgrep is not installed."
    ssdf_practice: ["PW.7.2", "PW.8.1"]

  - id: CTRL-004
    name: "Layer 1 structural/AST rules"
    layer: layer1
    mechanism: "check.py + ci_rules.yaml (ast_pattern, file_exists)"
    tool: "pcp check (pre-commit)"
    enforcement: hard_block
    description: "Deterministic pre-commit gate — modularity (MOD_*) and security (SEC_*) rules. A human can override a specific commit with `[pcp-bypass: reason]`; every bypass is logged (see CTRL-010) and this control's status for that commit is recorded as bypassed, not passed."
    ssdf_practice: ["PS.1.1", "PW.7.1"]

  - id: CTRL-005
    name: "Architect review (diff vs persona/architecture/KB)"
    layer: build-loop
    mechanism: "architect_review.py, called per-criterion and at wave boundaries"
    tool: "LLM judge (JUDGE_MODEL)"
    enforcement: hard_block
    description: "BLOCK-severity findings stop the build; a failed/erroring judge call is recorded as an error, not silently counted as a pass or a block."
    ssdf_practice: ["PW.1.3", "PW.4.1"]

  - id: CTRL-006
    name: "PR alignment vs objective/target_state"
    layer: layer2
    mechanism: "gate.py `pcp gate` (PR-time) and build.py's in-loop advisory check"
    tool: "LLM judge (JUDGE_MODEL)"
    enforcement: advisory
    description: "Never hard-blocks merge — score + regressions are logged for review."
    ssdf_practice: ["PW.2.1"]

  - id: CTRL-007
    name: "Wave contract validation"
    layer: wave-merge
    mechanism: "build.py:_run_wave_merge, dependency completeness check"
    tool: "n/a (deterministic)"
    enforcement: hard_block
    description: "Every declared inter-module dependency must have 100% complete acceptance criteria before the next dependency wave starts."
    ssdf_practice: ["PS.1.1"]

  - id: CTRL-008
    name: "Strategy coverage & coupling"
    layer: wave-merge
    mechanism: "validate_strategy.py, re-run at each wave boundary"
    tool: "LLM judge (coverage) + networkx graph math (coupling)"
    enforcement: hard_block
    description: "Coverage gaps or severe coupling violations (circular deps, God modules, shared state) block the next wave."
    ssdf_practice: ["PW.1.1"]

  - id: CTRL-009
    name: "Deploy phase exit criteria"
    layer: layer3
    mechanism: "deploy_check.py, SDLC_phase.yaml exit_criteria"
    tool: "n/a (deterministic)"
    enforcement: hard_block
    description: "Deterministic phase-exit gate — the only gate positioned right before a deploy action."
    ssdf_practice: ["PO.3.2", "PW.9.1"]

  - id: CTRL-010
    name: "Bypass accountability"
    layer: cross-cutting
    mechanism: "check.py bypass log"
    tool: "n/a"
    enforcement: override
    description: "A human can override CTRL-004 per-commit with `[pcp-bypass: reason]`. Every bypass is appended to bypass_log.yaml (reason + rules bypassed) and to telemetry.jsonl (result: bypassed) — never silent, always auditable."
    ssdf_practice: ["PO.5.1"]

  - id: CTRL-011
    name: "Session transcript archival"
    layer: cross-cutting
    mechanism: "capture.py archive_transcript()"
    tool: "n/a"
    enforcement: advisory
    description: "Every session transcript pcp capture is invoked on is copied (gzip-compressed) into .pcp/transcripts/ before classification runs — the full raw action record, not just the classifier's distilled BRD/decision-log summary, becomes part of this project's own durable evidence instead of living only in Claude Code's own ~/.claude/projects/ retention."
    ssdf_practice: ["PO.3.2"]

  - id: CTRL-012
    name: "Ticket automation (analyze/approve/reject/submit)"
    layer: cross-cutting
    mechanism: "program-context-protocol-team: tickets/analysis.py, tickets/actions.py"
    tool: "LLM judge (JUDGE_MODEL) for analysis; Temporal for submission"
    enforcement: advisory
    description: "A ticket ingested via program-context-protocol-team's webhook is analyzed (root-cause hypothesis + fix options), and every human decision (approve one option / reject) is recorded here, with the LLM's full raw analysis response stored as evidence — same as any other QA judge call. A human always decides; nothing in this control auto-picks an option."
    ssdf_practice: ["PW.4.1", "RV.1.1"]
"""

SDLC_PHASE_TEMPLATE = """\
version: "1.0"
current_phase: alpha
phases:
  - name: alpha
    exit_criteria:
      - id: E001
        description: "Core functionality implemented"
        check: manual
        status: pending
"""

DECOMPOSITION_TEMPLATE = """\
# Strategy Decomposition

## How the Objective Breaks Down

[Explain how the program objective decomposes into modules and why.]

## Module Dependency Order

1. [module-a] — [reason]
2. [module-b] — depends on module-a

## Inter-Module Contracts

[Describe what each module provides to others.]
"""

MODULE_SPEC_TEMPLATE = """\
version: "1.0"
module: {name}
description: "What this module does (10 words minimum)."
objective_coverage:
  - "Which part of objective.md this covers"
dependencies: []
constraints:
  - "List constraints here"
"""

MODULE_ACCEPTANCE_TEMPLATE = """\
version: "1.0"
module: {name}
criteria:
  # ── Modularity criteria (generated by pcp init — do not remove) ──────────
  - id: MOD_A001
    description: "Module can be removed without breaking other modules (drop test)"
    check: test_passes
    test: "tests/modularity/test_drop_{name}.sh"
    notes: "Temporarily disable module, run full test suite of other modules — must pass"
    status: pending

  - id: MOD_A002
    description: "Module registers through application interface, not via direct import"
    check: ast_pattern
    target: "src/main"
    pattern: "register\\\\({name}\\\\)|plugin\\\\({name}\\\\)|mount\\\\({name}\\\\)"
    status: pending

  - id: MOD_A003
    description: "Module has a feature flag (FEATURE_{name_upper}_ENABLED), default false"
    check: file_exists
    target: "src/modules/{name}/feature_flag.env"
    status: pending

  - id: MOD_A004
    description: "Module interface file exists and defines typed public surface"
    check: file_exists
    target: "src/interfaces/I{name_pascal}.ts"
    status: pending

  # ── Implementation criteria (add yours below) ─────────────────────────────
  - id: A001
    description: "Core implementation exists"
    check: manual
    status: pending
"""

ARCHITECT_PERSONA_TEMPLATE = """\
# Architect Persona

## Core Philosophy

Every module is a guest in the codebase. It can leave without drama.
It can arrive without surgery. Nothing else should know about it
except the application registry.

Vibe coders pivot. Architecture must absorb pivots without surgery.
Modularity is not a preference — it is a hard constraint.

## Modularity Invariants (always enforced, not project-specific)

BLOCK:
- Any direct import of another module's `src/` directory from outside that module
- Any module that imports from another module except through the `interfaces/` contract
- Any global mutable state shared between modules (singleton patterns, global stores)
- Any module that directly instantiates another module (use dependency injection via registry)
- Feature code shipped without a feature flag (`FEATURE_<MODULE>_ENABLED`)
- A module whose tests require another module to be present (tests must be isolated)
- Circular module dependencies (A depends on B depends on A)

WARN:
- A module with more than 3 entries in its `dependencies:` field (God module risk)
- A module that owns more than 3 database tables (God module risk)
- A module that directly modifies another module's database tables
- A non-trivial module (auth, payment, queue, scheduler, parser, embeddings,
  state-machine, ETL-class complexity) scaffolded with no prior-art check
  logged in `.pcp/decision_log.jsonl` — run `/priorart <description>` first
  and record reuse-as-dependency / fork-adapt / reference-pattern-only /
  build-fresh + license rationale before building

## Project-Specific Principles

BLOCK:
- [Add project-specific hard constraints here]
- Example: "No direct database calls outside repository layer"
- Example: "All external API calls go through a dedicated client module"

WARN:
- [Add project-specific design smells]
- Example: "Missing error boundary at integration points"
- Example: "Synchronous calls to external APIs without timeout"

## What I'm Lenient About

- [Things explicitly out of scope for this phase]
- Example: "Test coverage % in alpha phase"
- Example: "Internal naming conventions within a module (each module owns its internals)"

## Review Output
Rate each finding: BLOCK | WARN | NOTE
BLOCK = must fix before merge
WARN  = fix before ship
NOTE  = track, non-blocking
"""

PCP_CLAUDE_BLOCK_START = "<!-- PCP:BEGIN — auto-managed by `pcp init`, do not hand-edit this block -->"
PCP_CLAUDE_BLOCK_END = "<!-- PCP:END -->"

PCP_CLAUDE_BLOCK_BODY = """\
# PCP Governance (this project is PCP-managed)

This project uses PCP (Program Context Protocol). Every session — new or
resumed — is governed by `.pcp/`. Read the relevant files before acting;
do not restate or duplicate their content here.

## Read first, every session

- `.pcp/objective.md` — WHY this program exists. Immutable.
- `.pcp/target_state.md` — WHAT done looks like.
- `.pcp/architecture.md` — tech decisions + constraints.
- `.pcp/architect_persona.md` — modularity + review rules.
- `.pcp/current_state.md` — auto-generated reality snapshot.
- `.pcp/diff.md` — auto-computed gap vs target.
- `.pcp/strategy/decomposition.md` and `.pcp/strategy/modules/*/spec.yaml` — module specs.

## Hard rules (non-negotiable, all sessions)

1. **Spec files are human-written only** — `objective.md`, `target_state.md`,
   `architecture.md`, `modules/*/spec.yaml`, `modules/*/acceptance.yaml`.
   Never edit these as an agent. Propose changes via `pcp pm "<intent>"`.
2. **`current_state.md` is always auto-generated** by `pcp scan`. Never
   hand-write it.
3. **`diff.md` is always auto-computed** by `pcp diff`. Never edit it.
4. **Modularity is a hard constraint** — every module is a guest; it can
   leave without drama and arrive without surgery. No direct cross-module
   `src/` imports, no shared global mutable state, no module without a
   feature flag and an `interfaces/` contract. See `ci_rules.yaml` MOD_001-005.
5. Before committing, run `pcp check` (Layer 1). Before a PR, `pcp gate`
   (Layer 2, advisory). Before deploy, `pcp deploy-check` (Layer 3, hard).
   Bypass only via `[pcp-bypass: reason]` in the commit message — it is
   logged to `bypass_log.yaml`, never silent.
6. If work here changes program strategy (drop/add a module, change
   objective coverage), run `pcp validate-strategy` before proceeding.
7. Before scaffolding a non-trivial module (auth, payment, queue, scheduler,
   parser, embeddings, state-machine, ETL-class complexity), run
   `/priorart <description>` first — check for existing projects to reuse,
   fork, or reference before building from scratch. Log the decision
   (reuse-as-dependency / fork-adapt / reference-pattern-only / build-fresh
   + license) via `pcp capture` so it lands in `.pcp/decision_log.jsonl`.
   Skip for trivial modules (helpers, config parsers, glue code).

## Session start checklist

1. Read `.pcp/current_state.md` and `.pcp/diff.md` to know what's actually
   built vs. what's left — don't assume from memory or git log alone.
2. Read `.pcp/pcp.md` if present — it's the human-facing status rollup.
3. If mid-build, check `.pcp/telemetry.jsonl` (or run `pcp telemetry`) for
   prior attempt history on the current module before retrying.
"""


def render_pcp_claude_block() -> str:
    return f"{PCP_CLAUDE_BLOCK_START}\n{PCP_CLAUDE_BLOCK_BODY}{PCP_CLAUDE_BLOCK_END}"


def upsert_pcp_claude_block(claude_md_path: Path) -> bool:
    """Insert or refresh the PCP governance block in a project's CLAUDE.md.

    Preserves any human-authored content outside the marker pair. Returns
    True if the file was created or changed.
    """
    block = render_pcp_claude_block()
    if not claude_md_path.exists():
        claude_md_path.parent.mkdir(parents=True, exist_ok=True)
        claude_md_path.write_text(block + "\n")
        return True

    existing = claude_md_path.read_text()
    if PCP_CLAUDE_BLOCK_START in existing and PCP_CLAUDE_BLOCK_END in existing:
        pre = existing.split(PCP_CLAUDE_BLOCK_START)[0]
        post = existing.split(PCP_CLAUDE_BLOCK_END)[1]
        new_content = pre + block + post
    else:
        new_content = (existing.rstrip("\n") + "\n\n" + block + "\n") if existing.strip() else block + "\n"

    if new_content == existing:
        return False
    claude_md_path.write_text(new_content)
    return True


ADR_EXAMPLE = """\
# ADR-001: [Short Title]

## Status
Accepted | Superseded | Deprecated

## Context
[Why this decision was needed]

## Decision
[What was decided]

## Rationale
[Why this option over alternatives]

## Consequences
[What this enables. What it constrains.]
"""

POLICY_ESCALATION_TEMPLATE = """\
package pcp.escalation

# Confidence/stakes-gated routing: PCP's own asymmetric-failure-cost
# principle (never silently treat "unsure" as "safe to automate") --
# low confidence or an explicitly high-stakes action always escalates to
# a human rather than resolving through the agent by default.

default route := "agent"

route := "human" if input.confidence_score < 0.65
route := "human" if input.high_stakes == true
"""

POLICY_BYPASS_TEMPLATE = """\
package pcp.bypass

# Formalizes what ci_rules.yaml's [pcp-bypass: reason] mechanism treats as
# ad-hoc otherwise -- rejects placeholder reasons before pcp check treats
# a reason as adequate to log and accept a Layer 1 bypass.

default approved := false

approved if {
	count(trim_space(input.reason)) > 0
	not lower(trim_space(input.reason)) in {"reason", "todo", "test", "fixme"}
}
"""

POLICY_COUPLING_TEMPLATE = """\
package pcp.coupling

# Mirrors validate_strategy.py's display thresholds (green >= 0.8,
# yellow >= 0.6, else red) -- human-editable here instead of buried in
# Python.

coupling_color := "green" if input.coupling_score >= 0.8
else := "yellow" if input.coupling_score >= 0.6
else := "red"
"""

DOMAIN_KB_TEMPLATE = """\
# Domain Knowledge: [Technology/Area]

## Known Failure Modes

- [Pattern that causes bugs in this domain]

## Invariants

- [Things that must always be true]

## Gotchas

- [Non-obvious behaviours or edge cases]
"""


def _write(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


@click.command()
@click.option("--path", "project_path", type=click.Path(), default=".",
              help="Project root (default: current directory).")
@click.option("--module", "module_name", default=None,
              help="Also scaffold a module under strategy/modules/<name>/.")
@click.option("--force", is_flag=True, help="Overwrite existing files.")
def init(project_path: str, module_name: str | None, force: bool):
    """Scaffold .pcp/ directory in a project."""
    root = Path(project_path).resolve()
    pcp = root / ".pcp"

    files = {
        pcp / "objective.md": OBJECTIVE_TEMPLATE,
        pcp / "target_state.md": TARGET_STATE_TEMPLATE,
        pcp / "architecture.md": ARCHITECTURE_TEMPLATE,
        pcp / "ci_rules.yaml": CI_RULES_TEMPLATE,
        pcp / "controls.yaml": CONTROLS_TEMPLATE,
        pcp / "SDLC_phase.yaml": SDLC_PHASE_TEMPLATE,
        pcp / "strategy" / "decomposition.md": DECOMPOSITION_TEMPLATE,
        pcp / "architect_persona.md": ARCHITECT_PERSONA_TEMPLATE,
        pcp / "kb" / "adr" / "ADR-001-example.md": ADR_EXAMPLE,
        pcp / "kb" / "domain" / "general.md": DOMAIN_KB_TEMPLATE,
        pcp / "policies" / "escalation.rego": POLICY_ESCALATION_TEMPLATE,
        pcp / "policies" / "bypass_approval.rego": POLICY_BYPASS_TEMPLATE,
        pcp / "policies" / "coupling_threshold.rego": POLICY_COUPLING_TEMPLATE,
    }

    if module_name:
        mod_dir = pcp / "strategy" / "modules" / module_name
        files[mod_dir / "spec.yaml"] = MODULE_SPEC_TEMPLATE.format(name=module_name)
        files[mod_dir / "acceptance.yaml"] = MODULE_ACCEPTANCE_TEMPLATE.format(
            name=module_name, name_upper=module_name.upper(), name_pascal=_pascal_case(module_name),
        )

    created = []
    skipped = []
    for path, content in files.items():
        if _write(path, content, force):
            created.append(path.relative_to(root))
        else:
            skipped.append(path.relative_to(root))

    for p in created:
        console.print(f"  [green]created[/green]  {p}")
    for p in skipped:
        console.print(f"  [dim]skipped[/dim]  {p}  (exists, use --force to overwrite)")

    claude_md = root / "CLAUDE.md"
    if upsert_pcp_claude_block(claude_md):
        console.print(f"  [green]updated[/green]  CLAUDE.md  (PCP governance block)")
    else:
        console.print(f"  [dim]unchanged[/dim]  CLAUDE.md  (PCP governance block already current)")

    gitattributes = root / ".gitattributes"
    ga_lines = [
        ".pcp/current_state.md merge=ours",
        ".pcp/diff.md merge=ours",
        ".pcp/bypass_log.yaml merge=union",
    ]
    existing = gitattributes.read_text() if gitattributes.exists() else ""
    additions = [l for l in ga_lines if l not in existing]
    if additions:
        with open(gitattributes, "a") as f:
            f.write("\n" + "\n".join(additions) + "\n")
        console.print(f"  [green]updated[/green]  .gitattributes")

    # Layer 1 enforcement wired up automatically, not left as a manual step a
    # human could forget -- "this project has .pcp/" and "this project is
    # actually governed" used to be two separate facts. Cron side effects
    # (global intervention aggregation, skill upgrade check) deliberately
    # NOT included here -- see install_git_hook()'s own docstring.
    from pcp.commands.install_hook import install_git_hook
    hook_installed, hook_msg = install_git_hook(root)
    if hook_installed:
        console.print(f"  [green]installed[/green]  commit-msg hook  ({hook_msg})")
    else:
        console.print(f"  [dim]hook not installed[/dim]  ({hook_msg})")

    console.print(f"\n[bold]PCP initialised at {pcp}[/bold]")
    console.print("\nNext steps:")
    console.print("  1. Edit [cyan].pcp/objective.md[/cyan] — describe WHY this program exists")
    console.print("  2. Edit [cyan].pcp/strategy/decomposition.md[/cyan] — break objective into modules")
    console.print("  3. Run [cyan]pcp init --module <name>[/cyan] for each module")
    console.print("  4. Run [cyan]pcp validate-strategy[/cyan] to check coverage")
    console.print("  5. Edit [cyan].pcp/architect_persona.md[/cyan] — define architecture principles")
    console.print("  6. Add ADRs to [cyan].pcp/kb/adr/[/cyan] — document architecture decisions")
    console.print("  7. Run [cyan]pcp architect-review[/cyan] — review changes against persona")
