"""pcp observatory — human command-center view aggregating the Tier 2 layers
built so far: ontology (what exists/means, Phase A) and per-module build
status (initiative-level "what's happening"). Pure aggregation, same shape
as provenance.py — no LLM call, no rebuild, safe to call any time.

Honest about what isn't wired up yet, not faked: OPA (Phase B) is a
standalone policy engine today, not yet called from any real decision
point in pcp build/gate/deploy, so there is no persistent decision/
escalation history to show — that section stays empty until a future
phase actually wires OPA into a live gate. Only status words backed by
real available data are used (Delivered/On Track/Not Started) — "At Risk"
and "Needs You" would need real gate-failure/escalation signal this
aggregation doesn't have yet, so they're not fabricated here.
"""

import json
import sys
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, get_modules_dir, get_ontology_state, NoPCPDir
from pcp.commands.status import _load_modules_results, _parse_from_current_state
from pcp import policy as policy_lib

console = Console()


def _load_ontology_summary(pcp_dir: Path) -> dict:
    state_path = get_ontology_state(pcp_dir)
    if not state_path.exists():
        return {"available": False}
    state = yaml.safe_load(state_path.read_text()) or {}
    items = state.get("nodes", []) + state.get("edges", [])
    return {
        "available": True,
        "generated_at": state.get("generated_at"),
        "node_count": len(state.get("nodes", [])),
        "edge_count": len(state.get("edges", [])),
        "red": sum(1 for i in items if i.get("review_status") == "red"),
        "blue": sum(1 for i in items if i.get("review_status") == "blue"),
        "green": sum(1 for i in items if i.get("review_status") == "green"),
    }


def build_observatory(pcp_dir: Path) -> dict:
    """Pure aggregation — safe to call at any point, no side effects besides read.

    Reads completion status from current_state.md the same way `pcp status`'s
    fast path does — confirmed bug, caught by actually running this against
    a repo with 43/43 criteria complete: reusing only _load_modules_results
    (raw acceptance.yaml) without this overlay showed every module as "Not
    Started", since acceptance.yaml's own status field is the pre-scan
    default, not the actually-recorded outcome."""
    project_root = pcp_dir.parent
    modules_dir = get_modules_dir(pcp_dir)
    modules_results = _load_modules_results(modules_dir, project_root)
    statuses = _parse_from_current_state(pcp_dir / "current_state.md")
    for m in modules_results:
        for c in m["criteria"]:
            key = f"{m['module'].upper()}/{c['id']}"
            if key in statuses:
                c["status"] = statuses[key]

    initiatives = []
    for m in modules_results:
        total = len(m["criteria"])
        complete = sum(1 for c in m["criteria"] if c["status"] == "complete")
        if total == 0 or complete == total:
            status_word = "Delivered"
        elif complete == 0:
            status_word = "Not Started"
        else:
            status_word = "On Track"
        initiatives.append({
            "module": m["module"], "total": total, "complete": complete,
            "status_word": status_word,
            "pending": [c["id"] for c in m["criteria"] if c["status"] != "complete"],
        })

    return {
        "initiatives": initiatives,
        "ontology": _load_ontology_summary(pcp_dir),
        "policy_available": policy_lib.opa_available(),
        "decisions": [],
    }


def _render_markdown(data: dict) -> str:
    lines = [
        "# PCP Observatory",
        "",
        "> Auto-generated by `pcp observatory`. Aggregates ontology_state.yaml + "
        "module acceptance criteria + OPA availability. Do not edit manually.",
        "",
        "## Your Initiatives", "",
    ]
    if not data["initiatives"]:
        lines += ["_No modules found yet._", ""]
    else:
        for i in data["initiatives"]:
            lines.append(f"- **{i['module']}** — {i['status_word']} ({i['complete']}/{i['total']} criteria)")
        lines.append("")

    ont = data["ontology"]
    lines += ["## What's Happening (Ontology)", ""]
    if not ont.get("available"):
        lines += ["_No ontology extracted yet — run `pcp ontology-extract` first._", ""]
    else:
        lines += [
            f"Generated: {ont.get('generated_at', '?')} — "
            f"{ont['node_count']} nodes, {ont['edge_count']} edges",
            f"{ont['red']} red (unreviewed, low-confidence) — "
            f"{ont['blue']} blue (unreviewed, high-confidence) — "
            f"{ont['green']} green (human-verified)",
            "",
        ]

    lines += ["## Decisions", ""]
    if not data["policy_available"]:
        lines += ["_OPA not installed — decision/escalation history unavailable. "
                   "Install `opa` and see `pcp doctor`._", ""]
    elif not data["decisions"]:
        lines += ["_OPA is available, but not yet wired into a live gate — no decision "
                   "history exists yet. This section stays empty rather than fabricated "
                   "until a future phase actually routes a real decision through it._", ""]
    else:
        for d in data["decisions"]:
            lines.append(f"- {d}")
        lines.append("")

    return "\n".join(lines)


def write_observatory(pcp_dir: Path) -> Path:
    data = build_observatory(pcp_dir)
    md = _render_markdown(data)
    out = pcp_dir / "observatory.md"
    out.write_text(md)
    return out


@click.command()
@click.option("--path", "project_path", type=click.Path(), default=None)
@click.option("--json", "output_json", is_flag=True, help="Print raw JSON instead of writing observatory.md.")
def observatory(project_path: str | None, output_json: bool):
    """Human command-center view — initiatives, ontology, decisions (Tier 2)."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if output_json:
        click.echo(json.dumps(build_observatory(pcp_dir), indent=2, default=str))
        return

    out_path = write_observatory(pcp_dir)
    console.print(f"[green]Observatory written[/green] -> {out_path.relative_to(pcp_dir.parent)}")
