"""pcp provenance — audit-evidence document: every file, every gate PCP has
approved, any skipped/bypassed step made visible.

Pure aggregation over already-persisted logs (.pcp/controls.yaml,
.pcp/telemetry.jsonl, .pcp/bypass_log.yaml) — no LLM call, no rebuild.
Callable at any point in a project's lifecycle, cheap, always a live
snapshot. This is the SLSA/in-toto-informed "quality card" half of the
CMMC/SSDF-style build-evidence document — controls.py's control catalog is
the other half.
"""

import json
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, NoPCPDir
from pcp import telemetry as telemetry_mod

console = Console()

RESULT_SYMBOL = {
    "pass": "OK", "block": "BLOCK", "skipped": "skip", "error": "ERROR", "bypassed": "bypass",
}

# Fallback for telemetry records written before control_id existed (2026-07-01).
CHECK_TO_CONTROL = {
    "test-suite": "CTRL-001",
    "wave-test-suite": "CTRL-001",
    "lint": "CTRL-002",
    "sast": "CTRL-003",
    "layer1": "CTRL-004",
    "layer1-bypass": "CTRL-004",
    "architect-review": "CTRL-005",
    "wave-architect-review": "CTRL-005",
    "gate": "CTRL-006",
    "wave-contract": "CTRL-007",
    "wave-validate-strategy": "CTRL-008",
    "deploy-phase-exit": "CTRL-009",
}


def _load_controls(pcp_dir: Path) -> dict:
    path = pcp_dir / "controls.yaml"
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text()) or {}
    return {c["id"]: c for c in data.get("controls", [])}


def _load_bypasses(pcp_dir: Path) -> list[dict]:
    path = pcp_dir / "bypass_log.yaml"
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text()) or {}
    return data.get("bypasses", [])


def _git_head(project_root: Path) -> str:
    result = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True, cwd=project_root,
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def _control_id_for(record: dict) -> str | None:
    return record.get("control_id") or CHECK_TO_CONTROL.get(record.get("check"))


def build_provenance(pcp_dir: Path) -> dict:
    """Pure aggregation — safe to call at any point, no side effects besides read."""
    controls = _load_controls(pcp_dir)
    qa_records = [r for r in telemetry_mod.load(pcp_dir) if r.get("cycle") == "qa"]
    bypasses = _load_bypasses(pcp_dir)

    per_file: dict[str, dict[str, dict]] = defaultdict(dict)
    per_control: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))

    for r in qa_records:
        cid = _control_id_for(r)
        if not cid:
            continue
        result = r.get("result", "pass")
        per_control[cid]["total"] += 1
        per_control[cid][result] += 1
        for f in (r.get("files") or []):
            existing = per_file[f].get(cid)
            if not existing or r.get("timestamp", "") >= existing.get("timestamp", ""):
                per_file[f][cid] = r

    # A control whose every recorded outcome is "skipped" never actually ran
    # anywhere in this project — a project-wide blind spot, not per-file noise.
    standing_gap_cids = {
        cid for cid, totals in per_control.items()
        if totals["total"] > 0 and totals.get("skipped", 0) == totals["total"]
    }
    never_exercised_cids = {
        cid for cid in controls if cid not in per_control and cid != "CTRL-010"
    }

    return {
        "controls": controls,
        "per_file": {f: dict(v) for f, v in per_file.items()},
        "per_control": {cid: dict(v) for cid, v in per_control.items()},
        "standing_gap_cids": sorted(standing_gap_cids),
        "never_exercised_cids": sorted(never_exercised_cids),
        "bypasses": bypasses,
    }


def _render_markdown(project_root: Path, data: dict, timestamp: str) -> str:
    controls = data["controls"]
    per_file = data["per_file"]
    per_control = data["per_control"]

    lines = [
        "# PCP Audit Evidence",
        f"Generated: {timestamp} | Git: `{_git_head(project_root)}`",
        "",
        "> Auto-generated by `pcp provenance`. Aggregates `.pcp/controls.yaml` + "
        "`.pcp/telemetry.jsonl` + `.pcp/bypass_log.yaml`. Do not edit manually. "
        "SSDF mapping is informed, not a certified assessment.",
        "",
        "## Per-File Gate Coverage",
        "",
    ]

    if not per_file:
        lines += ["_No telemetry recorded yet — run `pcp build` first._", ""]
    else:
        control_ids = sorted(controls.keys()) or sorted({cid for f in per_file.values() for cid in f})
        lines.append("| File | " + " | ".join(control_ids) + " |")
        lines.append("|---|" + "---|" * len(control_ids))
        for f in sorted(per_file.keys()):
            row = [f"`{f}`"]
            for cid in control_ids:
                rec = per_file[f].get(cid)
                row.append("-" if not rec else RESULT_SYMBOL.get(rec.get("result"), rec.get("result", "?")))
            lines.append("| " + " | ".join(row) + " |")
        lines.append("")
        legend = ", ".join(f"`{cid}`={controls.get(cid, {}).get('name', cid)}" for cid in control_ids)
        lines += [f"Legend: {legend}", ""]

    lines += ["## Standing Gaps (control never actually ran project-wide)", ""]
    gap_lines = []
    for cid in data["standing_gap_cids"]:
        name = controls.get(cid, {}).get("name", cid)
        total = per_control.get(cid, {}).get("total", 0)
        gap_lines.append(f"- {cid} ({name}): {total}/{total} checks skipped — tool never detected project-wide.")
    for cid in data["never_exercised_cids"]:
        name = controls.get(cid, {}).get("name", cid)
        gap_lines.append(f"- {cid} ({name}): never invoked in this project yet.")
    lines += gap_lines if gap_lines else ["_None — every cataloged control has run with a real tool at least once._"]
    lines.append("")

    lines += ["## Bypass Ledger", ""]
    if data["bypasses"]:
        for b in data["bypasses"]:
            rules = ", ".join(b.get("rules_bypassed", []))
            lines.append(f"- `{b.get('timestamp', '')}` — {b.get('reason', '')} (rules: {rules})")
    else:
        lines.append("_No bypasses._")
    lines.append("")

    lines += ["## SSDF Crosswalk", "", "| Control | SSDF Practice | Enforcement | Status |", "|---|---|---|---|"]
    for cid, c in sorted(controls.items()):
        totals = per_control.get(cid, {})
        if cid == "CTRL-010":
            status = f"{len(data['bypasses'])} bypass(es) logged" if data["bypasses"] else "0 bypasses"
        elif cid in data["never_exercised_cids"]:
            status = "GAP — never invoked"
        elif cid in data["standing_gap_cids"]:
            status = "GAP — tool never detected"
        else:
            status = f"{totals.get('pass', 0)}/{totals.get('total', 0)} pass"
        practices = ", ".join(c.get("ssdf_practice", []))
        lines.append(f"| {cid} {c.get('name', '')} | {practices} | {c.get('enforcement', '')} | {status} |")
    lines.append("")

    return "\n".join(lines)


def write_provenance(pcp_dir: Path) -> Path:
    data = build_provenance(pcp_dir)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    md = _render_markdown(pcp_dir.parent, data, timestamp)
    out = pcp_dir / "provenance.md"
    out.write_text(md)
    return out


@click.command()
@click.option("--path", "project_path", type=click.Path(), default=None)
@click.option("--json", "output_json", is_flag=True, help="Print raw JSON instead of writing provenance.md.")
def provenance(project_path: str | None, output_json: bool):
    """Audit-evidence document — every file, every gate, any skip/bypass made visible."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if output_json:
        click.echo(json.dumps(build_provenance(pcp_dir), indent=2, default=str))
        return

    out_path = write_provenance(pcp_dir)
    console.print(f"[green]Provenance written[/green] -> {out_path.relative_to(pcp_dir.parent)}")
