"""pcp traceability — auto-generated requirement->module->criterion->test
rollup (IEEE/ISO 29148's SRS traceability requirement, made a real document
instead of only living in scattered deterministic checks). Same posture as
architecture_justification.md/provenance.md: pure aggregation over what's
already on disk (spec.yaml's objective_coverage + acceptance.yaml's
criteria), no LLM call, never hand-edited.

Deliberately traces at the granularity PCP's data model actually supports:
Requirement (an objective_coverage bullet) -> Module -> Criterion -> Test
target -> Status. There is no per-criterion link back to a specific
objective_coverage bullet in the schema (objective_coverage is a module-level
list, not tagged onto individual criteria) -- inventing a synthetic per-
criterion requirement ID here would be dishonest, not a real traceability
chain. What's shown is a module's declared coverage claims alongside what
was actually built and verified under that module, which is the real,
checkable relationship the schema supports."""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import click
import yaml
from rich.console import Console

from pcp.pcp_dir import find_pcp_dir, get_modules_dir, NoPCPDir

console = Console()


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError:
        return {}


def build_traceability(pcp_dir: Path) -> dict:
    """Pure aggregation, no LLM. Returns per-module objective_coverage claims
    alongside every criterion's test target/check/status/verified_by, plus
    program-wide totals."""
    modules_dir = get_modules_dir(pcp_dir)
    modules = []
    totals = {"total": 0, "complete": 0, "pending": 0, "other": 0}

    if modules_dir.exists():
        for mod_path in sorted(p for p in modules_dir.iterdir() if p.is_dir()):
            spec = _load_yaml(mod_path / "spec.yaml")
            acceptance = _load_yaml(mod_path / "acceptance.yaml")
            if not spec and not acceptance:
                continue

            criteria = []
            for c in acceptance.get("criteria", []) or []:
                if not isinstance(c, dict):
                    continue
                status = c.get("status", "pending")
                totals["total"] += 1
                if status == "complete":
                    totals["complete"] += 1
                elif status == "pending":
                    totals["pending"] += 1
                else:
                    totals["other"] += 1
                criteria.append({
                    "id": c.get("id"),
                    "description": c.get("description"),
                    "check": c.get("check"),
                    "target": c.get("target"),
                    "status": status,
                    "verified_by": c.get("verified_by"),
                })

            complete_count = sum(1 for c in criteria if c["status"] == "complete")
            modules.append({
                "module": mod_path.name,
                "objective_coverage": spec.get("objective_coverage") or [],
                "dependencies": spec.get("dependencies") or [],
                "criteria": criteria,
                "totals": {"total": len(criteria), "complete": complete_count},
            })

    return {"modules": modules, "totals": totals}


def _render_markdown(data: dict, timestamp: str) -> str:
    lines = [
        "# Traceability Matrix",
        "",
        f"_Auto-generated by `pcp traceability` at {timestamp}. Never hand-edit — "
        "sourced from each module's spec.yaml (`objective_coverage`) and "
        "acceptance.yaml (criteria); this is a rollup view, not a second place "
        "to author either._",
        "",
    ]

    t = data["totals"]
    pct = round(100 * t["complete"] / t["total"], 1) if t["total"] else 0.0
    lines.append(f"**Program-wide: {t['complete']}/{t['total']} criteria complete ({pct}%).**")
    lines.append("")

    if not data["modules"]:
        lines.append("_No modules found — nothing to trace yet._")
        return "\n".join(lines)

    lines.append("| Module | Criteria complete | Depends on |")
    lines.append("|---|---|---|")
    for m in data["modules"]:
        lines.append(
            f"| `{m['module']}` | {m['totals']['complete']}/{m['totals']['total']} "
            f"| {', '.join(m['dependencies']) or '—'} |"
        )
    lines.append("")

    for m in data["modules"]:
        lines.append(f"## Module: `{m['module']}`")
        lines.append("")
        if m["objective_coverage"]:
            lines.append("**Declared objective coverage:**")
            for cov in m["objective_coverage"]:
                lines.append(f"- {cov}")
            lines.append("")
        else:
            lines.append("_No objective_coverage declared for this module._")
            lines.append("")

        if m["criteria"]:
            lines.append("| Criterion | Check | Target | Status | Verified by |")
            lines.append("|---|---|---|---|---|")
            for c in m["criteria"]:
                lines.append(
                    f"| {c['id']}: {c['description']} | {c['check'] or '—'} "
                    f"| {c['target'] or '—'} | {c['status']} | {c['verified_by'] or '—'} |"
                )
        else:
            lines.append("_No criteria declared for this module._")
        lines.append("")

    return "\n".join(lines)


def write_traceability(pcp_dir: Path) -> Path:
    data = build_traceability(pcp_dir)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    md = _render_markdown(data, timestamp)
    out = pcp_dir / "traceability.md"
    out.write_text(md)
    return out


@click.command(name="traceability")
@click.option("--path", "project_path", type=click.Path(), default=None)
@click.option("--json", "output_json", is_flag=True, help="Print raw JSON instead of writing traceability.md.")
def traceability(project_path: str | None, output_json: bool):
    """Roll up objective-coverage -> module -> criterion -> test into traceability.md."""
    try:
        pcp_dir = find_pcp_dir(Path(project_path) if project_path else None)
    except NoPCPDir as e:
        console.print(f"[red]Error:[/red] {e}")
        sys.exit(2)

    if output_json:
        click.echo(json.dumps(build_traceability(pcp_dir), indent=2, default=str))
        return

    out_path = write_traceability(pcp_dir)
    console.print(f"[green]Traceability matrix written[/green] -> {out_path.relative_to(pcp_dir.parent)}")
