"""Control-catalog self-audit -- PCP applying its own philosophy to its own
catalog, not just to projects PCP builds. Real gap named in the 2026-07-21
self-evaluation: 33 CTRL checks accumulated with no pruning discipline to
match the modularity/token-discipline philosophy PCP preaches everywhere
else. Pure aggregation over `.pcp/controls.yaml` + `.pcp/telemetry.jsonl`,
no LLM, same posture as coverage_audit.py/architecture_justification.py --
surfaces a signal, never auto-prunes, never blocks.

Deliberately narrow: detects the ONE thing checkable without judgment --
a control declared in the catalog that has never once produced a real
finding across its recorded history (a `zero-findings` candidate for
human review: retire, merge into a related check, or leave as intentional
belt-and-suspenders coverage). Does NOT attempt automated mechanism-overlap
detection (e.g. "these three are all presence checks") -- that's a
judgment call a human should make reading the rendered report, not
something worth a fuzzy heuristic that could be wrong in either direction.
"""

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

# Below this many recorded runs, "zero findings" isn't a real signal yet --
# a brand-new control with 2 runs and no findings just hasn't been tested,
# not proven unnecessary.
MIN_RUNS_FOR_SIGNAL = 20


def _load_controls(pcp_dir: Path) -> list[dict]:
    path = pcp_dir / "controls.yaml"
    if not path.exists():
        return []
    try:
        data = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError:
        return []
    return data.get("controls", []) or []


def build_control_audit(pcp_dir: Path) -> dict:
    """Returns {control_id: {name, total_runs, findings, rate, layer,
    enforcement, signal}}. `signal` is one of: "insufficient-data" (below
    MIN_RUNS_FOR_SIGNAL), "never-fired" (>= MIN_RUNS_FOR_SIGNAL runs, zero
    findings -- retire/merge candidate), "active" (has fired at least
    once)."""
    from pcp import telemetry

    controls = _load_controls(pcp_dir)
    records = telemetry.load(pcp_dir)

    runs_by_control = defaultdict(int)
    findings_by_control = defaultdict(int)
    for r in records:
        cid = r.get("control_id")
        if not cid:
            continue
        runs_by_control[cid] += 1
        if r.get("result") == "block" or (r.get("error_count") or 0) > 0:
            findings_by_control[cid] += 1

    out = {}
    for c in controls:
        cid = c["id"]
        total = runs_by_control.get(cid, 0)
        findings = findings_by_control.get(cid, 0)
        if total < MIN_RUNS_FOR_SIGNAL:
            signal = "insufficient-data"
        elif findings == 0:
            signal = "never-fired"
        else:
            signal = "active"
        out[cid] = {
            "name": c.get("name", ""), "layer": c.get("layer", ""),
            "enforcement": c.get("enforcement", ""),
            "total_runs": total, "findings": findings,
            "rate": round(findings / total, 3) if total else None,
            "signal": signal,
        }
    return out


def render_markdown(audit: dict) -> str:
    lines = [
        "# Control Catalog Audit",
        "",
        "AUTO-GENERATED by `pcp control-audit`. Never edit -- regenerate instead.",
        "",
        "Pure aggregation over `.pcp/controls.yaml` + `.pcp/telemetry.jsonl`, no LLM. "
        f"A control needs at least {MIN_RUNS_FOR_SIGNAL} recorded runs before "
        "'never-fired' becomes a real signal rather than just untested.",
        "",
        "## Never-fired (retire/merge review candidates)",
        "",
    ]
    never_fired = {k: v for k, v in audit.items() if v["signal"] == "never-fired"}
    if not never_fired:
        lines.append("None -- every control with enough recorded runs has fired at least once.")
    else:
        lines.append("| Control | Name | Layer | Runs |")
        lines.append("|---|---|---|---|")
        for cid, v in sorted(never_fired.items()):
            lines.append(f"| {cid} | {v['name']} | {v['layer']} | {v['total_runs']} |")
    lines.append("")

    lines.append("## Full catalog")
    lines.append("")
    lines.append("| Control | Name | Layer | Enforcement | Runs | Findings | Rate | Signal |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for cid, v in sorted(audit.items()):
        rate = f"{v['rate']:.0%}" if v["rate"] is not None else "—"
        lines.append(
            f"| {cid} | {v['name']} | {v['layer']} | {v['enforcement']} | "
            f"{v['total_runs']} | {v['findings']} | {rate} | {v['signal']} |"
        )
    return "\n".join(lines) + "\n"


def write_control_audit(pcp_dir: Path) -> dict:
    audit = build_control_audit(pcp_dir)
    (pcp_dir / "control_audit.md").write_text(render_markdown(audit))
    return audit


def sync_catalog(pcp_dir: Path) -> list[str]:
    """Additive-only merge of the CURRENT package's control catalog into a
    project's existing controls.yaml. Real gap found 2026-07-22 auditing
    ontology-foundry: `controls.yaml` is scaffolded once at `pcp init` and
    never refreshed as the `pcp` package adds new controls over time -- one
    project had 23 distinct control_ids firing in telemetry.jsonl against a
    10-entry catalog, invisible to `pcp control-audit`/`pcp provenance`
    entirely. `pcp init --force` would fix this but also blindly overwrites
    objective.md/architecture.md/every other scaffolded file in the same
    pass -- far too destructive just to refresh a catalog. This only ever
    APPENDS entries whose id isn't already present; never rewrites, reorders,
    or removes an existing entry (a project may have hand-edited descriptions
    or removed a control deliberately -- this must not silently undo that).
    Returns the list of newly-added control ids; [] if the project's catalog
    is already current or has no controls.yaml at all (use `pcp init` to
    create one from scratch instead)."""
    from pcp.commands.init import CONTROLS_TEMPLATE

    path = pcp_dir / "controls.yaml"
    if not path.exists():
        return []

    template_controls = (yaml.safe_load(CONTROLS_TEMPLATE) or {}).get("controls", [])
    existing = _load_controls(pcp_dir)
    existing_ids = {c["id"] for c in existing}

    added = [c for c in template_controls if c["id"] not in existing_ids]
    if not added:
        return []

    data = yaml.safe_load(path.read_text()) or {}
    data["controls"] = existing + added
    path.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))
    return [c["id"] for c in added]
